sfx_agent_config:
  signalFxAccessToken: MyToken
  monitors:
    - type: cpu
    - type: filesystems
    - type: disk
    - type: net-io
    - type: load
    - type: memory
    - type: host-metadata
    - type: processlist
    - type: vmem
